POST localhost:3000/login
Content-Type: application/json

{
  "userName" :  "vvaudi",
  "password" : "secret"
}

###
GET localhost:5000/phone-book
Authorization: eyJraWQiOiIxMjMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX25hbWUiOiJ2dmF1ZGkiLCJmaXJzdF9uYW1lIjoiVmFsZXJpbyAxMjMiLCJsYXN0X25hbWUiOiJWYXVkaSIsImlhdCI6MTcyMDkwNzY4NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiZXhwIjoxNzIwOTExMjg2fQ.dgr_mSXzCvwOmoU-bNnfPBcLhweS9OUhOPCrWkT5V9bb3b8GqnQEztGg0sMfO35DPYTOWyTFCaG4EpoNgx1sJZRiPA8prvr35azSkWGEjhzw81YargGJwpojN9vWoN2OWaKlF5nSoy54hw5GH8rb7UqxN0t0s6XD7MVaVnssyRa1OdCt_gE8aiqMgq3lBrMTLNaezvKtwkOmAXaFEkjjBl0jT6QCL50j3A0tyZg_IEJXilrtu7hLJmPple5U6upFEi0ZFSI7iz0DfpbuyhnyWpDxPmfAz9ljveJJGujlH2jDDZEXsH_z-Or7UqroKiUybVKfHeUBTWlEhIqb14cUoerukoPtby1pQGfMb27JJmdkc-IOFbH4DyaCRl8WNyPjI9GHYe2RFVbbIP6SwF1xBvB3fhKxA_HUdqYpGQpZwfN-_reMdgAlH0BEVWkz1sa9YQ5dWNzSddnpVmS2Sdq-vyUaT_Kd_3mbXnCbbvmt17Yfx2P1tG64TyTerwBywEjVDNdDWMcXoUqRMAuC2KPKru2INvWQmpt2qSwURYShiEt9KSvrTTNdRgW94bMOwl2FCZU6wq7U_GblRJShm650MbpUVJXVlKkQ-Ujc-eOpwOMERx0qSf2xwEuQBp-345je33ZoHRhG0mDLRfLqj28Dbpj1xyPEFyC_sP-Z6q_h_kU

###
PUT localhost:5000/phone-book/MTIz
Content-Type: application/json

{
  "phone_number": "339 23 23 233",
  "birth_date": "2007-10-11"
}


###
PUT localhost:5000/phone-book/NDU2
Content-Type: application/json

{
  "phone_number": "339 32 32 233",
  "birth_date": "2027-11-10"
}


###
DELETE localhost:5000/phone-book/MTIz
