GET localhost:5000/phone-book
Authorization: eyJraWQiOiIxMjMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX25hbWUiOiJ2dmF1ZGkiLCJmaXJzdF9uYW1lIjoiVmFsZXJpbyAxMjMiLCJsYXN0X25hbWUiOiJWYXVkaSIsImlhdCI6MTcyMDg1NzM2NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdCIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QiLCJleHAiOjE3MjA4NjA5NjV9.RtSyBpC0U9DS2DZ1FuEmHAGwR4Snd9VUOru-tC70UCgOw5s9cp1RltutUra_xw_xCBTBMOhOiduRpfzsa8w3JmBTaKpJLVVAj8q6j2-BxscpWDg1RTlL3LC1N_xDd7paGzJpx8lj5airn732A6ICfa-mOB3-uOw3vRYzMOMqoE5PBLvYgvLEQJZcUeN2oWgHe28j0cCKNXEHq71yvH3ujY8DzShZsUQ3KmAJ62BOZYVvxm-WbnFPXGtgwCdfv9qwPbWwX8HE5H917M65cGBkTZ5oCkrb0RA_O65xztlTCfuuU2vRMxG3CkCU--QkmA177Eb0viylFACNWBXd9D0D38Tn4jdsPYgju2QNgqPBdkZmkcd4UEVMNB3VdYOsUeozsAKbqicBrUbh43a4EJL9V1B2vptV--njMWB-TWi9XbHIiSeiuX7Ptyae9Y0Ye0wbEirKruo721A2wPDgJBuymVwfw-kqqJIeh0i27Rw14qFl7Q-CMcdbP7S2QHGYItDPBjmUctK97897aHP3cc2IWaNhI7ZxTZibeLCP3vEjSMe7AVZROFRG4zvU3h2pZpUx7xhyzxJBO2b-ErNs63FP9RUp4s2XbUlEdZqqn82yJOJYI81Xnk71EqXrEKC6qsRZMBCFsnUuFLJKEPLK3YFTzW8tReRpOAmLj1mYM2adv8U

###
PUT localhost:5000/phone-book/MTIz
Content-Type: application/json

{
  "phone_number": "339 23 23 233",
  "birth_date": "2007-10-11"
}


###
PUT localhost:5000/phone-book/NDU2
Content-Type: application/json

{
  "phone_number": "339 32 32 233",
  "birth_date": "2027-11-10"
}


###
DELETE localhost:5000/phone-book/MTIz
