apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "phone-book-service.fullname" . }}
data:
  POSTGRESQL_USER: "{{ .Values.config.databaseUser }}"
  POSTGRESQL_PASSWORD: "{{ .Values.config.databasePassword }}"
  POSTGRESQL_HOST: "{{ .Values.config.databaseHost }}"
  POSTGRESQL_POST: "{{ .Values.config.databasePort }}"
  POSTGRESQL_DATABASE: "{{ .Values.config.database }}"
  PHONE_BOOK_AUD_CLAIM: "{{ .Values.config.jwtAudiance }}"
  ACCOUNT_SERVICE_ISS: "{{ .Values.config.jwtIssuer }}"