POST localhost:3000/login
Content-Type: application/json

{
  "userName" :  "vvaudi",
  "password" : "secret"
}

###
POST localhost:3000/account
Content-Type: application/json

{
  "userName" :  "vvaudi123",
  "password" : "secret",
  "firstName" : "Valerio",
  "lastName" : "Vaudi"

}

###
GET localhost:3000/jwks
